load("@rules_jvm_external//:specs.bzl", "maven")

REPOSITORIES = [
    "https://repo.maven.apache.org/maven2/",
]

ARTIFACTS = [
    maven.artifact("com.azure", "azure-core", "1.34.0"),
    maven.artifact("com.azure", "azure-core-http-netty", "1.12.7"),
    maven.artifact("com.azure", "azure-storage-blob", "12.20.1"),
    maven.artifact("com.azure", "azure-storage-common", "12.19.1"),
    maven.artifact("com.azure", "azure-storage-internal-avro", "12.5.1"),
    maven.artifact("com.fasterxml.jackson.core", "jackson-annotations", "2.13.4"),
    maven.artifact("com.fasterxml.jackson.core", "jackson-core", "2.13.4"),
    maven.artifact("com.fasterxml.jackson.core", "jackson-databind", "2.13.4.2"),
    maven.artifact("com.fasterxml.jackson.dataformat", "jackson-dataformat-xml", "2.13.4"),
    maven.artifact("com.fasterxml.jackson.datatype", "jackson-datatype-jsr310", "2.13.4"),
    maven.artifact("com.fasterxml.woodstox", "woodstox-core", "6.4.0"),
    maven.artifact("io.netty", "netty-buffer", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-codec", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-codec-dns", "4.1.81.Final"),
    maven.artifact("io.netty", "netty-codec-http", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-codec-http2", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-codec-socks", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-common", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-handler", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-handler-proxy", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-resolver", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-resolver-dns", "4.1.81.Final"),
    maven.artifact("io.netty", "netty-resolver-dns-classes-macos", "4.1.81.Final"),
    maven.artifact("io.netty", "netty-resolver-dns-native-macos", "4.1.81.Final", classifier = "osx-x86_64"),
    maven.artifact("io.netty", "netty-tcnative-boringssl-static", "2.0.54.Final"),
    maven.artifact("io.netty", "netty-tcnative-classes", "2.0.54.Final"),
    maven.artifact("io.netty", "netty-transport", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-transport-classes-epoll", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-transport-classes-kqueue", "4.1.82.Final"),
    maven.artifact("io.netty", "netty-transport-native-epoll", "4.1.82.Final", classifier = "linux-x86_64"),
    maven.artifact("io.netty", "netty-transport-native-kqueue", "4.1.82.Final", classifier = "osx-x86_64"),
    maven.artifact("io.netty", "netty-transport-native-unix-common", "4.1.82.Final"),
    maven.artifact("io.projectreactor.netty", "reactor-netty-core", "1.0.23"),
    maven.artifact("io.projectreactor.netty", "reactor-netty-http", "1.0.23"),
    maven.artifact("io.projectreactor", "reactor-core", "3.4.23"),
    maven.artifact("org.codehaus.woodstox", "stax2-api", "4.2.1"),
    maven.artifact("org.reactivestreams", "reactive-streams", "1.0.4"),
    maven.artifact("org.slf4j", "slf4j-api", "1.7.36"),
]
